In [1]:
#BUILD 1
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import v2

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])
)

train_dataloader = DataLoader(training_data, batch_size=64)
test_dataloader = DataLoader(test_data, batch_size=64)

100%|██████████| 26.4M/26.4M [00:02<00:00, 12.8MB/s]
100%|██████████| 29.5k/29.5k [00:00<00:00, 203kB/s]
100%|██████████| 4.42M/4.42M [00:01<00:00, 3.77MB/s]
100%|██████████| 5.15k/5.15k [00:00<00:00, 9.72MB/s]

### Custom Test Set Processing

In [19]:
import os

# 1. Find the file
print("Searching for test_set.zip...")
found_path = None
for root, dirs, files in os.walk('/content'):
    if 'test_set.zip' in files:
        found_path = os.path.join(root, 'test_set.zip')
        break

if not found_path:
    # Check root just in case
    if os.path.exists('/test_set.zip'):
        found_path = '/test_set.zip'

# 2. Extract it if found
if found_path:
    print(f"Success! Found file at: {found_path}")
    output_folder = 'test_set_images'
    os.makedirs(output_folder, exist_ok=True)
    !unzip -o "{found_path}" -d {output_folder}
    print("\nDone! You can now run the loading cell (786d274f).")
else:
    print("Could not find 'test_set.zip'. Please ensure the name is exactly 'test_set.zip' (case sensitive) and it finished uploading.")

Searching for test_set.zip...
Success! Found file at: /content/test_set.zip
Archive:  /content/test_set.zip
   creating: test_set_images/images/
  inflating: test_set_images/__MACOSX/._images
  inflating: test_set_images/images/002.png
  inflating: test_set_images/__MACOSX/images/._002.png
  inflating: test_set_images/images/016.png
  inflating: test_set_images/__MACOSX/images/._016.png
  inflating: test_set_images/images/017.png
  inflating: test_set_images/__MACOSX/images/._017.png
  inflating: test_set_images/images/003.png
  inflating: test_set_images/__MACOSX/images/._003.png
  inflating: test_set_images/images/029.png
  inflating: test_set_images/__MACOSX/images/._029.png
  inflating: test_set_images/images/015.png
  inflating: test_set_images/__MACOSX/images/._015.png
  inflating: test_set_images/images/001.png
  inflating: test_set_images/__MACOSX/images/._001.png
  inflating: test_set_images/images/000.png
  inflating: test_set_images/__MACOSX/images/._000.png
  inflating: test_set_images/images/014.png
  inflating: test_set_images/__MACOSX/images/._014.png
  inflating: test_set_images/images/028.png
  inflating: test_set_images/__MACOSX/images/._028.png
  inflating: test_set_images/images/010.png
  inflating: test_set_images/__MACOSX/images/._010.png
  inflating: test_set_images/images/004.png
  inflating: test_set_images/__MACOSX/images/._004.png
  inflating: test_set_images/images/038.png
  inflating: test_set_images/__MACOSX/images/._038.png
  inflating: test_set_images/images/039.png
  inflating: test_set_images/__MACOSX/images/._039.png
  inflating: test_set_images/images/005.png
  inflating: test_set_images/__MACOSX/images/._005.png
  inflating: test_set_images/images/011.png
  inflating: test_set_images/__MACOSX/images/._011.png
  inflating: test_set_images/images/007.png
  inflating: test_set_images/__MACOSX/images/._007.png
  inflating: test_set_images/images/013.png
  inflating: test_set_images/__MACOSX/images/._013.png
  inflating: test_set_images/images/012.png
  inflating: test_set_images/__MACOSX/images/._012.png
  inflating: test_set_images/images/006.png
  inflating: test_set_images/__MACOSX/images/._006.png
  inflating: test_set_images/images/049.png
  inflating: test_set_images/__MACOSX/images/._049.png
  inflating: test_set_images/images/061.png
  inflating: test_set_images/__MACOSX/images/._061.png
  inflating: test_set_images/images/075.png
  inflating: test_set_images/__MACOSX/images/._075.png
  inflating: test_set_images/images/074.png
  inflating: test_set_images/__MACOSX/images/._074.png
  inflating: test_set_images/images/060.png
  inflating: test_set_images/__MACOSX/images/._060.png
  inflating: test_set_images/images/048.png
  inflating: test_set_images/__MACOSX/images/._048.png
  inflating: test_set_images/images/076.png
  inflating: test_set_images/__MACOSX/images/._076.png
  inflating: test_set_images/images/062.png
  inflating: test_set_images/__MACOSX/images/._062.png
  inflating: test_set_images/images/089.png
  inflating: test_set_images/__MACOSX/images/._089.png
  inflating: test_set_images/images/088.png
  inflating: test_set_images/__MACOSX/images/._088.png
  inflating: test_set_images/images/063.png
  inflating: test_set_images/__MACOSX/images/._063.png
  inflating: test_set_images/images/077.png
  inflating: test_set_images/__MACOSX/images/._077.png
  inflating: test_set_images/images/073.png
  inflating: test_set_images/__MACOSX/images/._073.png
  inflating: test_set_images/images/067.png
  inflating: test_set_images/__MACOSX/images/._067.png
  inflating: test_set_images/images/098.png
  inflating: test_set_images/__MACOSX/images/._098.png
  inflating: test_set_images/images/099.png
  inflating: test_set_images/__MACOSX/images/._099.png
  inflating: test_set_images/images/066.png
  inflating: test_set_images/__MACOSX/images/._066.png
  inflating: test_set_images/images/072.png
  inflating: test_set_images/__MACOSX/images/._072.png
  inflating: test_set_images/images/064.png
  inflating: test_set_images/__MACOSX/images/._064.png
  inflating: test_set_images/images/070.png
  inflating: test_set_images/__MACOSX/images/._070.png
  inflating: test_set_images/images/058.png
  inflating: test_set_images/__MACOSX/images/._058.png
  inflating: test_set_images/images/059.png
  inflating: test_set_images/__MACOSX/images/._059.png
  inflating: test_set_images/images/071.png
  inflating: test_set_images/__MACOSX/images/._071.png
  inflating: test_set_images/images/065.png
  inflating: test_set_images/__MACOSX/images/._065.png
  inflating: test_set_images/images/068.png
  inflating: test_set_images/__MACOSX/images/._068.png
  inflating: test_set_images/images/040.png
  inflating: test_set_images/__MACOSX/images/._040.png
  inflating: test_set_images/images/054.png
  inflating: test_set_images/__MACOSX/images/._054.png
  inflating: test_set_images/images/083.png
  inflating: test_set_images/__MACOSX/images/._083.png
  inflating: test_set_images/images/097.png
  inflating: test_set_images/__MACOSX/images/._097.png
  inflating: test_set_images/images/096.png
  inflating: test_set_images/__MACOSX/images/._096.png
  inflating: test_set_images/images/082.png
  inflating: test_set_images/__MACOSX/images/._082.png
  inflating: test_set_images/images/055.png
  inflating: test_set_images/__MACOSX/images/._055.png
  inflating: test_set_images/images/041.png
  inflating: test_set_images/__MACOSX/images/._041.png
  inflating: test_set_images/images/069.png
  inflating: test_set_images/__MACOSX/images/._069.png
  inflating: test_set_images/images/057.png
  inflating: test_set_images/__MACOSX/images/._057.png
  inflating: test_set_images/images/043.png
  inflating: test_set_images/__MACOSX/images/._043.png
  inflating: test_set_images/images/094.png
  inflating: test_set_images/__MACOSX/images/._094.png
  inflating: test_set_images/images/080.png
  inflating: test_set_images/__MACOSX/images/._080.png
  inflating: test_set_images/images/081.png
  inflating: test_set_images/__MACOSX/images/._081.png
  inflating: test_set_images/images/095.png
  inflating: test_set_images/__MACOSX/images/._095.png
  inflating: test_set_images/images/042.png
  inflating: test_set_images/__MACOSX/images/._042.png
  inflating: test_set_images/images/056.png
  inflating: test_set_images/__MACOSX/images/._056.png
  inflating: test_set_images/images/052.png
  inflating: test_set_images/__MACOSX/images/._052.png
  inflating: test_set_images/images/046.png
  inflating: test_set_images/__MACOSX/images/._046.png
  inflating: test_set_images/images/091.png
  inflating: test_set_images/__MACOSX/images/._091.png
  inflating: test_set_images/images/085.png
  inflating: test_set_images/__MACOSX/images/._085.png
  inflating: test_set_images/images/084.png
  inflating: test_set_images/__MACOSX/images/._084.png
  inflating: test_set_images/images/090.png
  inflating: test_set_images/__MACOSX/images/._090.png
  inflating: test_set_images/images/047.png
  inflating: test_set_images/__MACOSX/images/._047.png
  inflating: test_set_images/images/053.png
  inflating: test_set_images/__MACOSX/images/._053.png
  inflating: test_set_images/images/045.png
  inflating: test_set_images/__MACOSX/images/._045.png
  inflating: test_set_images/images/051.png
  inflating: test_set_images/__MACOSX/images/._051.png
  inflating: test_set_images/images/079.png
  inflating: test_set_images/__MACOSX/images/._079.png
  inflating: test_set_images/images/086.png
  inflating: test_set_images/__MACOSX/images/._086.png
  inflating: test_set_images/images/092.png
  inflating: test_set_images/__MACOSX/images/._092.png
  inflating: test_set_images/images/093.png
  inflating: test_set_images/__MACOSX/images/._093.png
  inflating: test_set_images/images/087.png
  inflating: test_set_images/__MACOSX/images/._087.png
  inflating: test_set_images/images/078.png
  inflating: test_set_images/__MACOSX/images/._078.png
  inflating: test_set_images/images/050.png
  inflating: test_set_images/__MACOSX/images/._050.png
  inflating: test_set_images/images/044.png
  inflating: test_set_images/__MACOSX/images/._044.png
  inflating: test_set_images/images/023.png
  inflating: test_set_images/__MACOSX/images/._023.png
  inflating: test_set_images/images/037.png
  inflating: test_set_images/__MACOSX/images/._037.png
  inflating: test_set_images/images/036.png
  inflating: test_set_images/__MACOSX/images/._036.png
  inflating: test_set_images/images/022.png
  inflating: test_set_images/__MACOSX/images/._022.png
  inflating: test_set_images/images/008.png
  inflating: test_set_images/__MACOSX/images/._008.png
  inflating: test_set_images/images/034.png
  inflating: test_set_images/__MACOSX/images/._034.png
  inflating: test_set_images/images/020.png
  inflating: test_set_images/__MACOSX/images/._020.png
  inflating: test_set_images/images/021.png
  inflating: test_set_images/__MACOSX/images/._021.png
  inflating: test_set_images/images/035.png
  inflating: test_set_images/__MACOSX/images/._035.png
  inflating: test_set_images/images/009.png
  inflating: test_set_images/__MACOSX/images/._009.png
  inflating: test_set_images/images/031.png
  inflating: test_set_images/__MACOSX/images/._031.png
  inflating: test_set_images/images/025.png
  inflating: test_set_images/__MACOSX/images/._025.png
  inflating: test_set_images/images/019.png
  inflating: test_set_images/__MACOSX/images/._019.png
  inflating: test_set_images/images/018.png
  inflating: test_set_images/__MACOSX/images/._018.png
  inflating: test_set_images/images/024.png
  inflating: test_set_images/__MACOSX/images/._024.png
  inflating: test_set_images/images/030.png
  inflating: test_set_images/__MACOSX/images/._030.png
  inflating: test_set_images/images/026.png
  inflating: test_set_images/__MACOSX/images/._026.png
  inflating: test_set_images/images/032.png
  inflating: test_set_images/__MACOSX/images/._032.png
  inflating: test_set_images/images/033.png
  inflating: test_set_images/__MACOSX/images/._033.png
  inflating: test_set_images/images/027.png
  inflating: test_set_images/__MACOSX/images/._027.png

Done! You can now run the loading cell (786d274f).

In [23]:
import torch
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import v2
import os

# The unzip created 'test_set_images/images/'
# ImageFolder needs the path to the folder CONTAINING the category folders
base_path = 'test_set_images'

if not os.path.exists(os.path.join(base_path, 'images')):
    print(f"Error: Could not find the 'images' folder inside '{base_path}'.")
else:
    test_transforms = v2.Compose([
        v2.Resize((28, 28)),
        v2.Grayscale(num_output_channels=1),
        v2.ToImage(),
        v2.ToDtype(torch.float32, scale=True),
    ])

    # root=base_path will look inside for the 'images' folder and treat it as a class
    custom_test_dataset = datasets.ImageFolder(
        root=base_path,
        transform=test_transforms
    )

    custom_test_dataloader = DataLoader(custom_test_dataset, batch_size=64, shuffle=False)

    print(f"Successfully loaded {len(custom_test_dataset)} images from {base_path}/images/")

Successfully loaded 200 images from test_set_images/images/

In [4]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
class NeuralNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 256),
        nn.ReLU(),
        nn.Linear(256,128),
        nn.ReLU(),
        nn.Linear(128,64),
        nn.ReLU(),
        nn.Linear(64,32),
        nn.ReLU(),
        nn.Linear(32,10)
    )
  def forward(self, x):
    x = self.flatten(x)
    logits = self.relu_stack(x)
    return logits

ffn_model = NeuralNetwork().to(device)

In [5]:
loss_fn = nn.CrossEntropyLoss()


def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()
  for batch, (X,y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)
    pred = model(X)
    loss = loss_fn(pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")
def test(dataloader, model,loss_fn):
  model.eval()
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  test_loss, correct = 0, 0
  with torch.no_grad():
    for X,y in dataloader:
      X,y = X.to(device), y.to(device)
      pred = model(X)
      test_loss+=loss_fn(pred, y).item()
      correct += (pred.argmax(1) == y).type(torch.float).sum().item()
  test_loss /= num_batches
  correct /= size
  print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [6]:
ffn_optimizer = torch.optim.AdamW(ffn_model.parameters(), lr=1e-4)
epochs = 12
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, ffn_model, loss_fn, ffn_optimizer)
    test(test_dataloader, ffn_model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.297005  [    0/60000]
loss: 1.621856  [ 6400/60000]
loss: 0.873169  [12800/60000]
loss: 0.920570  [19200/60000]
loss: 0.830298  [25600/60000]
loss: 0.646160  [32000/60000]
loss: 0.776598  [38400/60000]
loss: 0.748672  [44800/60000]
loss: 0.678054  [51200/60000]
loss: 0.624107  [57600/60000]
Test Error:
 Accuracy: 76.6%, Avg loss: 0.652478

Epoch 2
-------------------------------
loss: 0.576052  [    0/60000]
loss: 0.712967  [ 6400/60000]
loss: 0.454294  [12800/60000]
loss: 0.613074  [19200/60000]
loss: 0.585358  [25600/60000]
loss: 0.452784  [32000/60000]
loss: 0.545067  [38400/60000]
loss: 0.712109  [44800/60000]
loss: 0.571638  [51200/60000]
loss: 0.506026  [57600/60000]
Test Error:
 Accuracy: 80.8%, Avg loss: 0.534492

Epoch 3
-------------------------------
loss: 0.426057  [    0/60000]
loss: 0.561771  [ 6400/60000]
loss: 0.388538  [12800/60000]
loss: 0.555132  [19200/60000]
loss: 0.499886  [25600/60000]
loss: 0.409664  [32000/60000]
loss: 0.428252  [38400/60000]
loss: 0.690134  [44800/60000]
loss: 0.552408  [51200/60000]
loss: 0.458595  [57600/60000]
Test Error:
 Accuracy: 83.0%, Avg loss: 0.484211

Epoch 4
-------------------------------
loss: 0.350294  [    0/60000]
loss: 0.506873  [ 6400/60000]
loss: 0.358793  [12800/60000]
loss: 0.507759  [19200/60000]
loss: 0.438576  [25600/60000]
loss: 0.380405  [32000/60000]
loss: 0.384079  [38400/60000]
loss: 0.675854  [44800/60000]
loss: 0.539881  [51200/60000]
loss: 0.442136  [57600/60000]
Test Error:
 Accuracy: 84.3%, Avg loss: 0.453025

Epoch 5
-------------------------------
loss: 0.302063  [    0/60000]
loss: 0.477587  [ 6400/60000]
loss: 0.339588  [12800/60000]
loss: 0.483922  [19200/60000]
loss: 0.392657  [25600/60000]
loss: 0.362347  [32000/60000]
loss: 0.368479  [38400/60000]
loss: 0.659168  [44800/60000]
loss: 0.526357  [51200/60000]
loss: 0.434698  [57600/60000]
Test Error:
 Accuracy: 84.9%, Avg loss: 0.432481

Epoch 6
-------------------------------
loss: 0.269623  [    0/60000]
loss: 0.453127  [ 6400/60000]
loss: 0.315568  [12800/60000]
loss: 0.466127  [19200/60000]
loss: 0.352849  [25600/60000]
loss: 0.350123  [32000/60000]
loss: 0.353428  [38400/60000]
loss: 0.640391  [44800/60000]
loss: 0.511237  [51200/60000]
loss: 0.435378  [57600/60000]
Test Error:
 Accuracy: 85.2%, Avg loss: 0.417718

Epoch 7
-------------------------------
loss: 0.248525  [    0/60000]
loss: 0.437882  [ 6400/60000]
loss: 0.301126  [12800/60000]
loss: 0.453216  [19200/60000]
loss: 0.322297  [25600/60000]
loss: 0.340330  [32000/60000]
loss: 0.337945  [38400/60000]
loss: 0.619325  [44800/60000]
loss: 0.496451  [51200/60000]
loss: 0.432575  [57600/60000]
Test Error:
 Accuracy: 85.4%, Avg loss: 0.406544

Epoch 8
-------------------------------
loss: 0.230292  [    0/60000]
loss: 0.422595  [ 6400/60000]
loss: 0.283651  [12800/60000]
loss: 0.437693  [19200/60000]
loss: 0.299484  [25600/60000]
loss: 0.334143  [32000/60000]
loss: 0.327429  [38400/60000]
loss: 0.600304  [44800/60000]
loss: 0.482742  [51200/60000]
loss: 0.425077  [57600/60000]
Test Error:
 Accuracy: 85.8%, Avg loss: 0.396814

Epoch 9
-------------------------------
loss: 0.215327  [    0/60000]
loss: 0.411350  [ 6400/60000]
loss: 0.270655  [12800/60000]
loss: 0.420822  [19200/60000]
loss: 0.283688  [25600/60000]
loss: 0.327818  [32000/60000]
loss: 0.315007  [38400/60000]
loss: 0.576589  [44800/60000]
loss: 0.463750  [51200/60000]
loss: 0.417487  [57600/60000]
Test Error:
 Accuracy: 86.1%, Avg loss: 0.388682

Epoch 10
-------------------------------
loss: 0.204720  [    0/60000]
loss: 0.392753  [ 6400/60000]
loss: 0.255857  [12800/60000]
loss: 0.403200  [19200/60000]
loss: 0.271215  [25600/60000]
loss: 0.320516  [32000/60000]
loss: 0.309357  [38400/60000]
loss: 0.558449  [44800/60000]
loss: 0.451233  [51200/60000]
loss: 0.408094  [57600/60000]
Test Error:
 Accuracy: 86.4%, Avg loss: 0.381639

Epoch 11
-------------------------------
loss: 0.197823  [    0/60000]
loss: 0.381867  [ 6400/60000]
loss: 0.245610  [12800/60000]
loss: 0.388351  [19200/60000]
loss: 0.259341  [25600/60000]
loss: 0.312293  [32000/60000]
loss: 0.298892  [38400/60000]
loss: 0.534938  [44800/60000]
loss: 0.428938  [51200/60000]
loss: 0.397355  [57600/60000]
Test Error:
 Accuracy: 86.6%, Avg loss: 0.374427

Epoch 12
-------------------------------
loss: 0.192247  [    0/60000]
loss: 0.373058  [ 6400/60000]
loss: 0.234139  [12800/60000]
loss: 0.372763  [19200/60000]
loss: 0.250259  [25600/60000]
loss: 0.310044  [32000/60000]
loss: 0.288989  [38400/60000]
loss: 0.513489  [44800/60000]
loss: 0.406409  [51200/60000]
loss: 0.384291  [57600/60000]
Test Error:
 Accuracy: 86.7%, Avg loss: 0.369447

Done!

In [7]:
#Build - 2
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import v2

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])
)

train_dataloader = DataLoader(training_data, batch_size=64)
test_dataloader = DataLoader(test_data, batch_size=64)

In [8]:
from torch.nn.modules.activation import ReLU
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"

class NeuralNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv_stack = nn.Sequential(
        nn.Conv2d(1, 32, kernel_size=3, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2, stride=2),
        nn.Conv2d(32, 64, kernel_size=3, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2, stride=2)
    )

    self.flatten = nn.Flatten()
    self.classifier = nn.Sequential(
        nn.Linear(64 * 7 * 7, 512),
        nn.ReLU(),
        nn.Linear(512, 256),
        nn.ReLU(),
        nn.Linear(256, 128),
        nn.ReLU(),
        nn.Linear(128, 64),
        nn.ReLU(),
        nn.Linear(64, 32),
        nn.ReLU(),
        nn.Linear(32, 10)
    )

  def forward(self, x):
    x = self.conv_stack(x)
    x = self.flatten(x)
    logits = self.classifier(x)
    return logits

cnn_model = NeuralNetwork().to(device)

In [9]:
epochs = 12

cnn_optimizer = torch.optim.AdamW(cnn_model.parameters(), lr=1e-4)

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, cnn_model, loss_fn, cnn_optimizer)
    test(test_dataloader, cnn_model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.299363  [    0/60000]
loss: 1.491589  [ 6400/60000]
loss: 0.940683  [12800/60000]
loss: 1.027929  [19200/60000]
loss: 0.789144  [25600/60000]
loss: 0.875829  [32000/60000]
loss: 0.742582  [38400/60000]
loss: 0.770038  [44800/60000]
loss: 0.632279  [51200/60000]
loss: 0.699264  [57600/60000]
Test Error:
 Accuracy: 76.6%, Avg loss: 0.643663

Epoch 2
-------------------------------
loss: 0.562933  [    0/60000]
loss: 0.786879  [ 6400/60000]
loss: 0.444520  [12800/60000]
loss: 0.660205  [19200/60000]
loss: 0.619714  [25600/60000]
loss: 0.531402  [32000/60000]
loss: 0.547917  [38400/60000]
loss: 0.628310  [44800/60000]
loss: 0.567710  [51200/60000]
loss: 0.567192  [57600/60000]
Test Error:
 Accuracy: 80.5%, Avg loss: 0.539407

Epoch 3
-------------------------------
loss: 0.459189  [    0/60000]
loss: 0.649953  [ 6400/60000]
loss: 0.354831  [12800/60000]
loss: 0.571829  [19200/60000]
loss: 0.536264  [25600/60000]
loss: 0.427027  [32000/60000]
loss: 0.468663  [38400/60000]
loss: 0.631740  [44800/60000]
loss: 0.526738  [51200/60000]
loss: 0.469870  [57600/60000]
Test Error:
 Accuracy: 82.1%, Avg loss: 0.488944

Epoch 4
-------------------------------
loss: 0.399541  [    0/60000]
loss: 0.546156  [ 6400/60000]
loss: 0.290716  [12800/60000]
loss: 0.535361  [19200/60000]
loss: 0.456858  [25600/60000]
loss: 0.379823  [32000/60000]
loss: 0.397964  [38400/60000]
loss: 0.654687  [44800/60000]
loss: 0.492191  [51200/60000]
loss: 0.418183  [57600/60000]
Test Error:
 Accuracy: 82.7%, Avg loss: 0.473356

Epoch 5
-------------------------------
loss: 0.360707  [    0/60000]
loss: 0.426151  [ 6400/60000]
loss: 0.260717  [12800/60000]
loss: 0.522442  [19200/60000]
loss: 0.421587  [25600/60000]
loss: 0.371917  [32000/60000]
loss: 0.343442  [38400/60000]
loss: 0.665089  [44800/60000]
loss: 0.473782  [51200/60000]
loss: 0.382355  [57600/60000]
Test Error:
 Accuracy: 84.0%, Avg loss: 0.440888

Epoch 6
-------------------------------
loss: 0.312123  [    0/60000]
loss: 0.352268  [ 6400/60000]
loss: 0.238114  [12800/60000]
loss: 0.486590  [19200/60000]
loss: 0.372710  [25600/60000]
loss: 0.363722  [32000/60000]
loss: 0.307935  [38400/60000]
loss: 0.632209  [44800/60000]
loss: 0.467634  [51200/60000]
loss: 0.345470  [57600/60000]
Test Error:
 Accuracy: 85.2%, Avg loss: 0.411001

Epoch 7
-------------------------------
loss: 0.269202  [    0/60000]
loss: 0.312828  [ 6400/60000]
loss: 0.216906  [12800/60000]
loss: 0.449009  [19200/60000]
loss: 0.344115  [25600/60000]
loss: 0.360511  [32000/60000]
loss: 0.282393  [38400/60000]
loss: 0.623741  [44800/60000]
loss: 0.441516  [51200/60000]
loss: 0.320318  [57600/60000]
Test Error:
 Accuracy: 86.0%, Avg loss: 0.394102

Epoch 8
-------------------------------
loss: 0.244869  [    0/60000]
loss: 0.294953  [ 6400/60000]
loss: 0.197495  [12800/60000]
loss: 0.417011  [19200/60000]
loss: 0.313741  [25600/60000]
loss: 0.360397  [32000/60000]
loss: 0.270361  [38400/60000]
loss: 0.607677  [44800/60000]
loss: 0.417409  [51200/60000]
loss: 0.295224  [57600/60000]
Test Error:
 Accuracy: 86.9%, Avg loss: 0.377029

Epoch 9
-------------------------------
loss: 0.230021  [    0/60000]
loss: 0.283857  [ 6400/60000]
loss: 0.182050  [12800/60000]
loss: 0.389191  [19200/60000]
loss: 0.293130  [25600/60000]
loss: 0.357287  [32000/60000]
loss: 0.260211  [38400/60000]
loss: 0.581964  [44800/60000]
loss: 0.388853  [51200/60000]
loss: 0.277110  [57600/60000]
Test Error:
 Accuracy: 87.4%, Avg loss: 0.359794

Epoch 10
-------------------------------
loss: 0.216616  [    0/60000]
loss: 0.271885  [ 6400/60000]
loss: 0.172330  [12800/60000]
loss: 0.366416  [19200/60000]
loss: 0.275664  [25600/60000]
loss: 0.360698  [32000/60000]
loss: 0.250439  [38400/60000]
loss: 0.552954  [44800/60000]
loss: 0.362190  [51200/60000]
loss: 0.264917  [57600/60000]
Test Error:
 Accuracy: 87.6%, Avg loss: 0.350284

Epoch 11
-------------------------------
loss: 0.211746  [    0/60000]
loss: 0.255060  [ 6400/60000]
loss: 0.165471  [12800/60000]
loss: 0.347294  [19200/60000]
loss: 0.255256  [25600/60000]
loss: 0.359893  [32000/60000]
loss: 0.248926  [38400/60000]
loss: 0.518757  [44800/60000]
loss: 0.337510  [51200/60000]
loss: 0.257947  [57600/60000]
Test Error:
 Accuracy: 88.2%, Avg loss: 0.335920

Epoch 12
-------------------------------
loss: 0.198128  [    0/60000]
loss: 0.241211  [ 6400/60000]
loss: 0.163275  [12800/60000]
loss: 0.327581  [19200/60000]
loss: 0.235638  [25600/60000]
loss: 0.360701  [32000/60000]
loss: 0.244377  [38400/60000]
loss: 0.481064  [44800/60000]
loss: 0.317388  [51200/60000]
loss: 0.243465  [57600/60000]
Test Error:
 Accuracy: 88.3%, Avg loss: 0.331031

Done!

### Processing and Predicting on Custom Test Set

In [21]:
import os

# Create a directory to extract the images into
output_folder = 'test_set_images'
os.makedirs(output_folder, exist_ok=True)

# Unzip the file into the new directory
print(f"Unzipping test_set.zip into {output_folder}/")
!unzip -o test_set.zip -d {output_folder}

Unzipping test_set.zip into test_set_images/
Archive:  test_set.zip
  inflating: test_set_images/__MACOSX/._images
  inflating: test_set_images/images/002.png
  inflating: test_set_images/__MACOSX/images/._002.png
  inflating: test_set_images/images/016.png
  inflating: test_set_images/__MACOSX/images/._016.png
  inflating: test_set_images/images/017.png
  inflating: test_set_images/__MACOSX/images/._017.png
  inflating: test_set_images/images/003.png
  inflating: test_set_images/__MACOSX/images/._003.png
  inflating: test_set_images/images/029.png
  inflating: test_set_images/__MACOSX/images/._029.png
  inflating: test_set_images/images/015.png
  inflating: test_set_images/__MACOSX/images/._015.png
  inflating: test_set_images/images/001.png
  inflating: test_set_images/__MACOSX/images/._001.png
  inflating: test_set_images/images/000.png
  inflating: test_set_images/__MACOSX/images/._000.png
  inflating: test_set_images/images/014.png
  inflating: test_set_images/__MACOSX/images/._014.png
  inflating: test_set_images/images/028.png
  inflating: test_set_images/__MACOSX/images/._028.png
  inflating: test_set_images/images/010.png
  inflating: test_set_images/__MACOSX/images/._010.png
  inflating: test_set_images/images/004.png
  inflating: test_set_images/__MACOSX/images/._004.png
  inflating: test_set_images/images/038.png
  inflating: test_set_images/__MACOSX/images/._038.png
  inflating: test_set_images/images/039.png
  inflating: test_set_images/__MACOSX/images/._039.png
  inflating: test_set_images/images/005.png
  inflating: test_set_images/__MACOSX/images/._005.png
  inflating: test_set_images/images/011.png
  inflating: test_set_images/__MACOSX/images/._011.png
  inflating: test_set_images/images/007.png
  inflating: test_set_images/__MACOSX/images/._007.png
  inflating: test_set_images/images/013.png
  inflating: test_set_images/__MACOSX/images/._013.png
  inflating: test_set_images/images/012.png
  inflating: test_set_images/__MACOSX/images/._012.png
  inflating: test_set_images/images/006.png
  inflating: test_set_images/__MACOSX/images/._006.png
  inflating: test_set_images/images/049.png
  inflating: test_set_images/__MACOSX/images/._049.png
  inflating: test_set_images/images/061.png
  inflating: test_set_images/__MACOSX/images/._061.png
  inflating: test_set_images/images/075.png
  inflating: test_set_images/__MACOSX/images/._075.png
  inflating: test_set_images/images/074.png
  inflating: test_set_images/__MACOSX/images/._074.png
  inflating: test_set_images/images/060.png
  inflating: test_set_images/__MACOSX/images/._060.png
  inflating: test_set_images/images/048.png
  inflating: test_set_images/__MACOSX/images/._048.png
  inflating: test_set_images/images/076.png
  inflating: test_set_images/__MACOSX/images/._076.png
  inflating: test_set_images/images/062.png
  inflating: test_set_images/__MACOSX/images/._062.png
  inflating: test_set_images/images/089.png
  inflating: test_set_images/__MACOSX/images/._089.png
  inflating: test_set_images/images/088.png
  inflating: test_set_images/__MACOSX/images/._088.png
  inflating: test_set_images/images/063.png
  inflating: test_set_images/__MACOSX/images/._063.png
  inflating: test_set_images/images/077.png
  inflating: test_set_images/__MACOSX/images/._077.png
  inflating: test_set_images/images/073.png
  inflating: test_set_images/__MACOSX/images/._073.png
  inflating: test_set_images/images/067.png
  inflating: test_set_images/__MACOSX/images/._067.png
  inflating: test_set_images/images/098.png
  inflating: test_set_images/__MACOSX/images/._098.png
  inflating: test_set_images/images/099.png
  inflating: test_set_images/__MACOSX/images/._099.png
  inflating: test_set_images/images/066.png
  inflating: test_set_images/__MACOSX/images/._066.png
  inflating: test_set_images/images/072.png
  inflating: test_set_images/__MACOSX/images/._072.png
  inflating: test_set_images/images/064.png
  inflating: test_set_images/__MACOSX/images/._064.png
  inflating: test_set_images/images/070.png
  inflating: test_set_images/__MACOSX/images/._070.png
  inflating: test_set_images/images/058.png
  inflating: test_set_images/__MACOSX/images/._058.png
  inflating: test_set_images/images/059.png
  inflating: test_set_images/__MACOSX/images/._059.png
  inflating: test_set_images/images/071.png
  inflating: test_set_images/__MACOSX/images/._071.png
  inflating: test_set_images/images/065.png
  inflating: test_set_images/__MACOSX/images/._065.png
  inflating: test_set_images/images/068.png
  inflating: test_set_images/__MACOSX/images/._068.png
  inflating: test_set_images/images/040.png
  inflating: test_set_images/__MACOSX/images/._040.png
  inflating: test_set_images/images/054.png
  inflating: test_set_images/__MACOSX/images/._054.png
  inflating: test_set_images/images/083.png
  inflating: test_set_images/__MACOSX/images/._083.png
  inflating: test_set_images/images/097.png
  inflating: test_set_images/__MACOSX/images/._097.png
  inflating: test_set_images/images/096.png
  inflating: test_set_images/__MACOSX/images/._096.png
  inflating: test_set_images/images/082.png
  inflating: test_set_images/__MACOSX/images/._082.png
  inflating: test_set_images/images/055.png
  inflating: test_set_images/__MACOSX/images/._055.png
  inflating: test_set_images/images/041.png
  inflating: test_set_images/__MACOSX/images/._041.png
  inflating: test_set_images/images/069.png
  inflating: test_set_images/__MACOSX/images/._069.png
  inflating: test_set_images/images/057.png
  inflating: test_set_images/__MACOSX/images/._057.png
  inflating: test_set_images/images/043.png
  inflating: test_set_images/__MACOSX/images/._043.png
  inflating: test_set_images/images/094.png
  inflating: test_set_images/__MACOSX/images/._094.png
  inflating: test_set_images/images/080.png
  inflating: test_set_images/__MACOSX/images/._080.png
  inflating: test_set_images/images/081.png
  inflating: test_set_images/__MACOSX/images/._081.png
  inflating: test_set_images/images/095.png
  inflating: test_set_images/__MACOSX/images/._095.png
  inflating: test_set_images/images/042.png
  inflating: test_set_images/__MACOSX/images/._042.png
  inflating: test_set_images/images/056.png
  inflating: test_set_images/__MACOSX/images/._056.png
  inflating: test_set_images/images/052.png
  inflating: test_set_images/__MACOSX/images/._052.png
  inflating: test_set_images/images/046.png
  inflating: test_set_images/__MACOSX/images/._046.png
  inflating: test_set_images/images/091.png
  inflating: test_set_images/__MACOSX/images/._091.png
  inflating: test_set_images/images/085.png
  inflating: test_set_images/__MACOSX/images/._085.png
  inflating: test_set_images/images/084.png
  inflating: test_set_images/__MACOSX/images/._084.png
  inflating: test_set_images/images/090.png
  inflating: test_set_images/__MACOSX/images/._090.png
  inflating: test_set_images/images/047.png
  inflating: test_set_images/__MACOSX/images/._047.png
  inflating: test_set_images/images/053.png
  inflating: test_set_images/__MACOSX/images/._053.png
  inflating: test_set_images/images/045.png
  inflating: test_set_images/__MACOSX/images/._045.png
  inflating: test_set_images/images/051.png
  inflating: test_set_images/__MACOSX/images/._051.png
  inflating: test_set_images/images/079.png
  inflating: test_set_images/__MACOSX/images/._079.png
  inflating: test_set_images/images/086.png
  inflating: test_set_images/__MACOSX/images/._086.png
  inflating: test_set_images/images/092.png
  inflating: test_set_images/__MACOSX/images/._092.png
  inflating: test_set_images/images/093.png
  inflating: test_set_images/__MACOSX/images/._093.png
  inflating: test_set_images/images/087.png
  inflating: test_set_images/__MACOSX/images/._087.png
  inflating: test_set_images/images/078.png
  inflating: test_set_images/__MACOSX/images/._078.png
  inflating: test_set_images/images/050.png
  inflating: test_set_images/__MACOSX/images/._050.png
  inflating: test_set_images/images/044.png
  inflating: test_set_images/__MACOSX/images/._044.png
  inflating: test_set_images/images/023.png
  inflating: test_set_images/__MACOSX/images/._023.png
  inflating: test_set_images/images/037.png
  inflating: test_set_images/__MACOSX/images/._037.png
  inflating: test_set_images/images/036.png
  inflating: test_set_images/__MACOSX/images/._036.png
  inflating: test_set_images/images/022.png
  inflating: test_set_images/__MACOSX/images/._022.png
  inflating: test_set_images/images/008.png
  inflating: test_set_images/__MACOSX/images/._008.png
  inflating: test_set_images/images/034.png
  inflating: test_set_images/__MACOSX/images/._034.png
  inflating: test_set_images/images/020.png
  inflating: test_set_images/__MACOSX/images/._020.png
  inflating: test_set_images/images/021.png
  inflating: test_set_images/__MACOSX/images/._021.png
  inflating: test_set_images/images/035.png
  inflating: test_set_images/__MACOSX/images/._035.png
  inflating: test_set_images/images/009.png
  inflating: test_set_images/__MACOSX/images/._009.png
  inflating: test_set_images/images/031.png
  inflating: test_set_images/__MACOSX/images/._031.png
  inflating: test_set_images/images/025.png
  inflating: test_set_images/__MACOSX/images/._025.png
  inflating: test_set_images/images/019.png
  inflating: test_set_images/__MACOSX/images/._019.png
  inflating: test_set_images/images/018.png
  inflating: test_set_images/__MACOSX/images/._018.png
  inflating: test_set_images/images/024.png
  inflating: test_set_images/__MACOSX/images/._024.png
  inflating: test_set_images/images/030.png
  inflating: test_set_images/__MACOSX/images/._030.png
  inflating: test_set_images/images/026.png
  inflating: test_set_images/__MACOSX/images/._026.png
  inflating: test_set_images/images/032.png
  inflating: test_set_images/__MACOSX/images/._032.png
  inflating: test_set_images/images/033.png
  inflating: test_set_images/__MACOSX/images/._033.png
  inflating: test_set_images/images/027.png
  inflating: test_set_images/__MACOSX/images/._027.png

#### Generate Predictions for Custom Test Set using FFN Model

In [25]:
import pandas as pd
import torch
import os

# Check if the dataloader exists before proceeding
if 'custom_test_dataloader' not in locals():
    print("Error: 'custom_test_dataloader' is not defined. Please ensure the data loading cell (786d274f) has run successfully.")
else:
    ffn_model.to(device)
    ffn_model.eval()

    custom_ffn_predictions = []
    custom_ffn_image_filenames = []

    # ImageFolder might include the __MACOSX files which cause crashes.
    # We will iterate through the dataset and only predict on valid images.
    with torch.no_grad():
        for i in range(len(custom_test_dataset)):
            image_path, _ = custom_test_dataset.samples[i]
            filename = os.path.basename(image_path)

            # Skip hidden macOS metadata files
            if filename.startswith('._'):
                continue

            # Load and predict individual image
            input_tensor, _ = custom_test_dataset[i]
            input_tensor = input_tensor.unsqueeze(0).to(device) # Add batch dimension

            output = ffn_model(input_tensor)
            pred = output.argmax(1).item()

            custom_ffn_predictions.append(pred)
            custom_ffn_image_filenames.append(os.path.splitext(filename)[0])

    # Create a DataFrame
    custom_ffn_results_df = pd.DataFrame({
        'image_id': custom_ffn_image_filenames,
        'label': custom_ffn_predictions
    })

    custom_ffn_output_filename = '2025CS11175_NN.csv'
    custom_ffn_results_df.to_csv(custom_ffn_output_filename, index=False)

    print(f"Successfully processed {len(custom_ffn_predictions)} valid images.")
    print(f"Predictions saved to {custom_ffn_output_filename}")
    display(custom_ffn_results_df.head())

Successfully processed 100 valid images.
Predictions saved to 2025CS11175_NN.csv

  image_id  label
0      000      5
1      001      3
2      002      7
3      003      4
4      004      3

#### Generate Predictions for Custom Test Set using CNN Model

In [27]:
import pandas as pd
import torch
import os

# Safety check: only run if the dataloader was successfully created
if 'custom_test_dataloader' not in locals():
    print("Error: 'custom_test_dataloader' is not defined. Please ensure the data loading cell (786d274f) runs successfully.")
else:
    # Ensure the cnn_model is in evaluation mode and on the correct device
    cnn_model.to(device)
    cnn_model.eval()

    custom_cnn_predictions = []
    custom_cnn_image_filenames = []

    # Iterate through the dataset manually to skip hidden macOS files
    with torch.no_grad():
        for i in range(len(custom_test_dataset)):
            image_path, _ = custom_test_dataset.samples[i]
            filename = os.path.basename(image_path)

            # Skip hidden macOS metadata files
            if filename.startswith('._'):
                continue

            # Load and predict individual image
            input_tensor, _ = custom_test_dataset[i]
            input_tensor = input_tensor.unsqueeze(0).to(device)

            output = cnn_model(input_tensor)
            pred = output.argmax(1).item()

            custom_cnn_predictions.append(pred)
            custom_cnn_image_filenames.append(os.path.splitext(filename)[0])

    # Create a DataFrame with image IDs and predictions for CNN
    custom_cnn_results_df = pd.DataFrame({
        'image_id': custom_cnn_image_filenames,
        'label': custom_cnn_predictions
    })

    custom_cnn_output_filename = '2025CS11175_CNN.csv'
    custom_cnn_results_df.to_csv(custom_cnn_output_filename, index=False)

    print(f"Successfully processed {len(custom_cnn_predictions)} valid images for CNN.")
    print(f"Predictions saved to {custom_cnn_output_filename}")
    display(custom_cnn_results_df.head())

Successfully processed 100 valid images for CNN.
Predictions saved to 2025CS11175_CNN.csv

  image_id  label
0      000      5
1      001      1
2      002      7
3      003      4
4      004      3